apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: xfsnowpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xfsnowpipelinesjavascriptdocker 
    spec:
      containers:
        - name: xfsnowpipelinesjavascriptdocker 
          image: mythcr.azurecr.io/xfsnowpipelinesjavascriptdocker
          ports:
          - containerPort: 8080