apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      containers:
        - name: helloworld
          image: snowpeak.azurecr.cn/helloworld:1.3
          ports:
          - containerPort: 80
          #健康检查，通过 httpGet 检查应用运行状态
          livenessProbe:   
            httpGet:
              port: 80
              scheme: HTTP
              path: /
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 3
